// Panel C supplies the biological relationships. Intensities, durations and
// spatial distances below are illustration controls, not measured kinetics.
const state = (ca, ros, damage, signals, approach, contact, pruning, activation = .05) => ({
  ca, ros, damage, signals, approach, contact, pruning, activation,
});

export const microgliaMechanism = {
  id: 'microglia',
  title: 'Remodelado microglial',
  subtitle: 'Participación de la microglía en la eliminación de sinapsis dañadas',
  description: 'Una conexión alterada, señales locales y el acercamiento de la microglía.',
  navLabel: 'Microglía',
  eyebrow: '04 / MICROGLÍA · PANEL C',
  heading: ['Conexiones bajo', 'vigilancia.'],
  scaleIndex: '04',
  scaleLabel: 'MICROAMBIENTE SINÁPTICO',
  isolatedContext: true,
  resetOnExit: true,
  // Visual response rates keep extension and retraction legible across a stage.
  // They are not biological rate constants; existing modules retain their pace.
  responseRates: { approach: .4, contact: .65, pruning: .28, damage: .7, signals: .8 },
  portraitFit: .93,
  entryCamera: 'damagedSpine',
  overviewCamera: 'microgliaOverview',
  initialState: state(0, 0, 0, 0, 0, 0, 0),
  cameraPoses: {
    microgliaOverview: { position: [5, 3.5, 24.5], target: [.2, .6, 0] },
    healthySynapse: { position: [3.4, 2.9, 23], target: [.3, .25, 0] },
    damagedSpine: { position: [3.2, 1.7, 18.5], target: [.65, -.75, .1] },
    complementSignals: { position: [3.5, 1.5, 18.5], target: [1.0, -.6, .1] },
    microgliaApproach: { position: [5.5, 4.2, 23], target: [1.3, .9, -.1] },
    microgliaContact: { position: [4.8, 2.4, 21], target: [1.35, -.15, .1] },
    postPruningOverview: { position: [5.1, 3.5, 24.5], target: [.2, .45, 0] },
  },
  steps: [
    {
      key: 'functional-synapse',
      title: 'Sinapsis dendrítica',
      caption: 'Dos espinas conservan su forma y sus contactos. Cerca de ellas, la microglía explora el entorno con movimientos discretos de sus procesos.',
      duration: 8,
      state: state(0, 0, 0, 0, 0, 0, 0),
      camera: 'healthySynapse',
      labels: ['healthySpine', 'terminal', 'microglia'],
    },
    {
      key: 'synaptic-alteration',
      title: 'Una conexión cambia de estado',
      caption: 'En una de las espinas aumenta la entrada de Ca²⁺ por NMDAR y la señal de ROS. La espina vecina conserva su morfología.',
      duration: 9,
      state: state(.78, .6, .12, 0, 0, 0, 0, .8),
      camera: 'damagedSpine',
      labels: ['nmda', 'calcium', 'ros'],
    },
    {
      key: 'damage-associated-signals',
      title: 'Señales en la sinapsis alterada',
      caption: 'C1q y C3 aparecen asociados a la superficie de la conexión alterada. En su interior, la caspasa-3 aporta una señal local relacionada con cambios de espinas y dendritas.',
      duration: 10,
      state: state(.7, .68, .28, .9, 0, 0, 0, .7),
      camera: 'complementSignals',
      labels: ['damagedSpine', 'c1q', 'c3', 'caspase3'],
    },
    {
      key: 'microglial-recognition',
      title: 'Un proceso se aproxima',
      caption: 'Un proceso microglial se extiende hacia la conexión alterada mientras el soma conserva su posición. La espina vecina permanece al margen del contacto.',
      duration: 11,
      state: state(.58, .6, .32, 1, .9, 0, 0, .62),
      camera: 'microgliaApproach',
      labels: ['microglia', 'process', 'damagedSpine'],
    },
    {
      key: 'contact-remodeling',
      title: 'Contacto y remodelado',
      caption: 'El proceso alcanza la región sináptica. La cabeza de la espina se reduce y retrae gradualmente: una representación conceptual del remodelado local.',
      duration: 12,
      state: state(.42, .48, .45, .9, 1, 1, .7, .48),
      camera: 'microgliaContact',
      labels: ['process', 'damagedSpine', 'healthySpine'],
    },
    {
      key: 'connectivity-remodeling',
      title: 'Remodelado de la conectividad sináptica',
      caption: 'La conexión en estudio se reduce mientras la vecina conserva su estructura. Una eliminación excesiva de conexiones durante el desarrollo puede alterar la organización de los circuitos neuronales.',
      duration: 10,
      state: state(.18, .28, .58, .5, 1, 1, .93, .26),
      camera: 'postPruningOverview',
      labels: ['microglia', 'healthySpine', 'dendrite'],
    },
  ],
  content: {
    microglia: {
      category: 'VIGILANCIA DEL ENTORNO NEURONAL',
      title: 'Microglía',
      text: 'Célula inmunitaria residente del sistema nervioso central. Sus procesos exploran el entorno y pueden participar en el remodelado de conexiones sinápticas.',
      detail: 'La vigilancia microglial también forma parte del entorno cerebral sano: sus prolongaciones pueden moverse mientras el cuerpo celular permanece relativamente estable. En este recorrido, esa exploración precede a un contacto localizado con una conexión alterada. La comparación con la espina vecina ayuda a distinguir el remodelado de una sinapsis de un cambio general de toda la neurona.',
      observe: 'Compara la posición estable del cuerpo celular con sus ramificaciones, especialmente la que se aproxima a la espina.',
      note: 'El contacto microglial no implica siempre eliminación ni daño neuronal.',
    },
    process: {
      category: 'CONTACTO ENTRE CÉLULAS',
      title: 'Proceso microglial',
      text: 'Una prolongación fina y ramificada que puede extenderse o retraerse. Aquí se aproxima gradualmente a la sinapsis alterada sin desplazar todo el soma.',
      detail: 'La ramificación permite explorar regiones próximas y establecer contactos localizados. La secuencia concentra el movimiento en un proceso distal: primero reduce su distancia a la espina y después alcanza su superficie. El contacto y la reducción posterior representan una posibilidad de remodelado; la exploración microglial puede tener otros resultados según el estado de la conexión y del entorno.',
      observe: 'Sigue el extremo que avanza hacia la espina y distingue la aproximación, el contacto y la reducción posterior.',
      note: 'La trayectoria y su duración son recursos de ilustración.',
    },
    healthySpine: {
      category: 'REFERENCIA MORFOLÓGICA',
      title: 'Espina conservada',
      text: 'Esta espina mantiene su cabeza, cuello y contacto sináptico durante el recorrido. Permite comparar los cambios de la conexión vecina.',
      detail: 'Las dos espinas comparten una rama dendrítica, pero la ilustración concentra los cambios en una sola de ellas. Mantener una referencia estable permite reconocer la escala local del proceso: cambian la forma y el contacto de una conexión, mientras otra permanece visible. La comparación muestra morfología; la actividad eléctrica de estas sinapsis queda fuera de la escena.',
      observe: 'Compara su cabeza y cuello con los de la espina en estudio antes, durante y después del contacto microglial.',
      note: 'Su conservación visual no representa una medición de función sináptica.',
    },
    damagedSpine: {
      category: 'CONEXIÓN EN REMODELADO',
      title: 'Espina en estudio',
      text: 'Comienza con una morfología conservada. En las etapas siguientes presenta señales asociadas con daño, contacto microglial y reducción gradual de su cabeza.',
      detail: 'El recorrido reúne cambios de calcio, ROS, complemento y caspasa-3 en una región sináptica, siguiendo las relaciones de la figura. Cada componente aporta un aspecto del estado local; su coexistencia no demuestra una cadena única de causas. La reducción gradual permite seguir la pérdida de volumen de esa conexión manteniendo como referencia la dendrita y la espina vecina.',
      observe: 'Observa los cambios de contorno y contacto con la terminal, manteniendo a la vista la espina vecina.',
      note: 'El recorrido ilustra una posibilidad del panel C, no el destino de toda espina alterada.',
    },
    c1q: {
      category: 'COMPONENTE DEL COMPLEMENTO',
      title: 'C1q',
      text: 'C1q es un componente del complemento relacionado con el refinamiento de conexiones en determinados contextos. Aquí se sitúa junto a la sinapsis alterada para representar la relación indicada en la figura.',
      detail: 'En estudios del sistema visual de ratón en desarrollo, C1q y C3 participan en la eliminación y el refinamiento de conexiones. Ese resultado sitúa al complemento dentro de procesos de organización de circuitos, además de su contexto inmunitario. En la escena, pocos complejos próximos a la superficie destacan una asociación local; interpretarlos requiere considerar el estado y el entorno de la sinapsis.',
      observe: 'Localiza los pequeños complejos ramificados junto a la superficie de la espina y distingue su forma de los marcadores C3.',
      note: 'La forma es estilizada; su presencia no diagnostica por sí sola daño sináptico.',
    },
    c3: {
      category: 'COMPONENTE DEL COMPLEMENTO',
      title: 'C3',
      text: 'Componente del complemento que participa en procesos de remodelado sináptico. El panel C lo sitúa entre las señales asociadas con la conexión alterada.',
      detail: 'La participación de C3 en el refinamiento de conexiones se ha estudiado junto con el complemento y la microglía en circuitos visuales en desarrollo. Aquí su marcador permite reconocer esa relación dentro del entorno de una espina. La escena organiza los componentes en etapas para facilitar la lectura, aunque su presencia no determina por sí sola el destino de cada conexión.',
      observe: 'Compara los marcadores compactos de C3 con los complejos ramificados de C1q sobre la misma región sináptica.',
      note: 'El marcador resume C3 y su participación funcional, sin representar sus fragmentos ni receptores.',
    },
    caspase3: {
      category: 'SEÑAL LOCAL ASOCIADA CON DAÑO',
      title: 'Caspasa-3 · CASP3',
      text: 'La caspasa-3 puede participar localmente en cambios de espinas y dendritas. Aquí acompaña el estado alterado de la conexión indicado en el panel C.',
      detail: 'Experimentos en neuronas han mostrado que la actividad de caspasa-3 puede relacionarse con eliminación local de espinas y retracción dendrítica sin muerte de toda la célula. Esta distinción permite interpretar una señal situada en un compartimento concreto. El recorrido conserva CASP3 dentro de la región alterada y presenta el complemento en la superficie como componentes con papeles diferentes.',
      observe: 'Localiza CASP3 dentro de la región alterada y compárala con C1q y C3, asociados a su superficie.',
      note: 'No se presenta como señal extracelular que atraiga microglía ni como apoptosis de toda la neurona.',
    },
    nmda: {
      category: 'CONTEXTO POSTSINÁPTICO',
      title: 'NMDAR',
      text: 'Receptor que permite entrada de Ca²⁺ cuando se cumplen sus condiciones de activación. Su actividad aporta aquí el contexto inicial de la alteración sináptica.',
      observe: 'Busca el receptor en la cabeza de la espina en estudio y sigue la entrada de calcio por su canal.',
      note: 'Este recorrido se centra en la interacción con la microglía.',
    },
    calcium: {
      category: 'SEÑAL INTRACELULAR',
      title: 'Ca²⁺ · calcio',
      text: 'La entrada aumentada de Ca²⁺ acompaña el cambio de estado de la espina en el panel C. Las partículas atraviesan el canal NMDAR hacia el interior.',
      observe: 'Sigue las partículas desde el canal hacia el interior de la espina y observa su localización frente a la vecina.',
      note: 'Su cantidad no representa una concentración ni un umbral de daño.',
    },
    ros: {
      category: 'ESTRÉS OXIDATIVO LOCAL',
      title: 'ROS · especies reactivas de oxígeno',
      text: 'Esta señal reúne conceptualmente especies reactivas de oxígeno asociadas con el entorno de la sinapsis alterada.',
      observe: 'Localiza la señal de ROS en torno a la espina en estudio y compara ambas conexiones durante las primeras etapas.',
      note: 'El módulo no atribuye una fuente molecular única ni añade rutas de producción.',
    },
    glutamate: {
      category: 'CONTEXTO SINÁPTICO',
      title: 'Glutamato',
      text: 'Neurotransmisor excitador liberado hacia la hendidura sináptica. Su presencia contextualiza la activación del receptor y la entrada de calcio.',
      note: 'La liberación se simplifica para mantener el foco en la relación microglía–sinapsis.',
    },
    terminal: {
      category: 'COMPARTIMENTO PRESINÁPTICO',
      title: 'Terminal presináptica',
      text: 'El extremo de un axón establece contacto con la cabeza de la espina a través de la hendidura sináptica.',
      note: 'Su menor protagonismo durante el remodelado es una convención de lectura.',
    },
    dendrite: {
      category: 'CONTINUIDAD NEURONAL',
      title: 'Dendrita',
      text: 'La rama neuronal sostiene las espinas mostradas. El cambio local de una conexión no implica la desaparición de toda la dendrita o de la neurona.',
      note: 'Las proporciones y distancias facilitan la lectura del microambiente.',
    },
  },
  async createScene(context) {
    const { createMicrogliaEnvironment } = await import('../scene/microglia-environment.js');
    return createMicrogliaEnvironment(context);
  },
};

export default microgliaMechanism;
