// These explanations also remain accessible when WebGL is unavailable.
export const structures = {
  glutamate: { category: 'NEUROTRANSMISOR', title: 'Glutamato', text: 'Las vesículas de la terminal presináptica liberan glutamato en la hendidura. Su unión a receptores postsinápticos participa en la comunicación excitadora. Una señal excesiva o prolongada puede comprometer la regulación del calcio y favorecer mecanismos de excitotoxicidad.', note: 'La recaptación y la participación de los astrocitos no se representan.' },
  ampa: { category: 'RECEPTOR IONOTRÓPICO', title: 'Receptor AMPA', text: 'AMPA media gran parte de la transmisión excitadora rápida. El flujo de cationes, principalmente Na⁺ y K⁺, contribuye a despolarizar la membrana. Esta despolarización puede favorecer el alivio del bloqueo por Mg²⁺ del receptor NMDA. La permeabilidad al Ca²⁺ depende de la composición del receptor.', note: 'Las subunidades se estilizan; no es una reconstrucción molecular.' },
  nmda: { category: 'RECEPTOR IONOTRÓPICO', title: 'Receptor NMDA', text: 'Su apertura requiere glutamato, un coagonista y condiciones de voltaje que alivien el bloqueo por Mg²⁺. Permite el paso de Ca²⁺ y otros cationes. La actividad regulada participa en plasticidad; una actividad excesiva o sostenida puede contribuir a la sobrecarga celular.', note: 'La localización y el contexto de activación importan. Mg²⁺ y coagonistas se omiten en la escena.' },
  calcium: { category: 'SEÑAL INTRACELULAR', title: 'Entrada de Ca²⁺', text: 'El calcio que entra por NMDA participa en señales necesarias para la función sináptica. Cuando su entrada supera la capacidad de regulación, puede acumularse y alterar procesos celulares. La mitocondria participa en ese equilibrio; una carga excesiva puede comprometer su función.', note: 'El tamaño, el número y la velocidad de los iones son ilustrativos.' },
  mitochondria: { category: 'ORGÁNULO · VISTA EN CORTE', title: 'Mitocondria', text: 'La membrana interna se pliega en crestas, donde se organiza parte de la maquinaria que produce ATP. Las mitocondrias también participan en la regulación del calcio. Una sobrecarga puede alterar la función energética y el equilibrio redox, con consecuencias para la célula.', note: 'Se sitúa en la espina por claridad didáctica; no es una localización universal.' },
  ros: { category: 'EQUILIBRIO REDOX', title: 'Estrés oxidativo', text: 'Las especies reactivas de oxígeno (ROS) participan en procesos fisiológicos. Cuando su producción supera las defensas antioxidantes, pueden contribuir al daño de lípidos, proteínas y ácidos nucleicos. La disfunción mitocondrial y las alteraciones redox pueden reforzarse mutuamente.', note: 'Los puntos magenta indican actividad conceptual, no moléculas a escala.' },
  caspases: { category: 'VÍAS DE DAÑO', title: 'Señalización de daño', text: 'Las caspasas son proteasas que participan en algunas rutas de muerte celular. Aquí se representan como complejos conceptuales para explorar la señalización asociada al daño. La excitotoxicidad puede involucrar varias vías, incluidas vías independientes de caspasas; la muerte neuronal no es un desenlace inevitable.', note: 'No se representa una secuencia única, exclusiva ni predictiva.' },
};
export const steps = [
  { key: 'glutamate', caption: '01 — Las vesículas liberan glutamato hacia la hendidura sináptica. La señal alcanza los receptores de la espina.' },
  { key: 'nmda', caption: '02 — AMPA contribuye a la despolarización; NMDA integra la unión de agonistas y las condiciones de voltaje.' },
  { key: 'calcium', caption: '03 — El Ca²⁺ entra por NMDA. Una entrada sostenida puede superar la capacidad de regulación intracelular.' },
  { key: 'ros', caption: '04 — La sobrecarga puede alterar la función mitocondrial y el equilibrio redox; estos procesos se retroalimentan.' },
  { key: 'caspases', caption: '05 — Pueden activarse vías de daño, algunas asociadas a caspasas. La progresión no es única ni inevitable.' },
];
export const modeCaptions = {
  physiological: 'Una señal esencial para comunicar neuronas. Explora qué ocurre cuando se pierde su regulación.',
  overload: 'Una activación excesiva o sostenida puede asociarse con sobrecarga de Ca²⁺, alteración mitocondrial y vías de daño.',
};
